Repository Pepelelipa/MacroChallenge, pull requests merged in 2020-10, with the labels that each got.

#22 Changing reload data to invalidate layout
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: enhancement

#23 feat/notebookSelectionDesign
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspaceCellNotebookCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookView.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCellNotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: enhancement

#24 Hotfix/invalidate layout when appear
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
Labels: bug

#27 Feat/displaying notebook notes
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/NotebookIndexTableViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
Labels: enhancement

#25 Feat/adding workspace
  MacroPepelelipa/.swiftLint.yml
  MacroPepelelipa/Database/Mockup/Mockdata.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/btnWorkspaceBackground.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/btnWorkspaceBackground.imageset/btnWorkspaceBackground.pdf
Labels: enhancement

#29 Feat/text box
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/BoxView.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/AddingBoxViewDelegateObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/CGPointExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/CGRectExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/CornerEnum.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/ResizeHandleView.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/TextEditingDelegateObserver.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
Labels: documentation, enhancement

#30 Feat/text edit modal
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToogleButton.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
Labels: documentation, enhancement

#31 Feat/italic button
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/TextEditingDelegateObserver.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
Labels: enhancement

#32 Feat/error treatment
  MacroPepelelipa/Database/Mockup/Mockdata.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/ErrorAlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/PhotoPicker/MarkupPhotoPickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/ResizeHandleView.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspaceCellNotebookCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextField.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: documentation, enhancement

#34 Feat/adding images
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/IsAddingImageDelegateObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Markup/ImageBoxView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
Labels: documentation, enhancement

#33 Feat/adding notebook
  MacroPepelelipa/Database/Mockup/Mockdata.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/NotebooksCollectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PopupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/ColorSelectionCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Colors.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/AddNotebook/ColorSelectionCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb0.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb1.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb10.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb11.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb12.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb13.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb18.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb19.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb2.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb20.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb21.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb22.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb23.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb3.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb4.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb6.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb7.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb8.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Colors.xcassets/Notebook Colors/nb9.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Workspace/AddNotebook/ColorSelectionCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: enhancement

#35 Feat/bold button
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Extensions/UIFont+Traits.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
Labels: documentation, enhancement

#36 Feat/adding highlight text to input view
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/IsAddingImageDelegateObserver.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
Labels: documentation, enhancement

#37 Feat/i pad navigation bar
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/SplitView/SplitViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupNavigationBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupNavigationView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H1.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H2.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H3.imageset/Contents.json
Labels: documentation, enhancement

#39 Feat/text color
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
Labels: documentation, enhancement

#40 Feat/feedbacks
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/AddNewSpaceTextFieldDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/AddWorkspaceObserver.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/AddNewSpaceToolBar.swift
Labels: documentation, enhancement

#41 Adding missing documentation
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
Labels: documentation

#42 Feat/pop over
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupNavigationView.swift
Labels: documentation, enhancement

#43 Feat/text font
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/Fonts.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Header/MarkdownHeader+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/MarkdownParser+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/View/Fonts/DancingScript/DancingScript-Bold.ttf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/DancingScript/DancingScript-Regular.ttf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/Merriweather/Merriweather-Bold.otf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/Merriweather/Merriweather-BoldItalic.otf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/Merriweather/Merriweather-Italic.otf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/Merriweather/Merriweather-Regular.otf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/OpenSans/OpenSans-Bold.ttf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/OpenSans/OpenSans-BoldItalic.ttf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/OpenSans/OpenSans-Italic.ttf
  MacroPepelelipa/MacroPepelelipa/View/Fonts/OpenSans/OpenSans-Regular.ttf
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
Labels: documentation, enhancement

#44 Feat/fixing pop up
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupNavigationView.swift
Labels: documentation, enhancement

#46 Hotfix/duplicated code
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/ErrorAlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Fonts.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Lists/MarkdownList.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupFormatView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H1.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H2.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H3.imageset/Contents.json
Labels: documentation, enhancement

#47 Feat/delete notebook
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/AlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/ErrorAlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: bug, documentation, enhancement

#48 Feat/fonts
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Fonts.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownParser.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Header/MarkdownHeader+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextField.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: enhancement

#55 Feat/continuous scroll
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/PhotoPicker/PhotoEditingViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexObserverDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/NotebookIndexTableViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/ImageButtonObserver.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesPageViewControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/NotebookIndex/TableViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/NotesPageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H1.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H2.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H3.imageset/Contents.json
Labels: bug, documentation, enhancement

#56 Bugfix/selected text error
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H1.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H2.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/H3.imageset/Contents.json
Labels: enhancement

#57 Feat/adding data persistence
  MacroPepelelipa/Database/Data/CoreData/CoreDataController.swift
  MacroPepelelipa/Database/Data/DataManager.swift
  MacroPepelelipa/Database/EntityProtocols/ImageBoxEntity.swift
  MacroPepelelipa/Database/EntityProtocols/TextBoxEntity.swift
  MacroPepelelipa/Database/Model/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  MacroPepelelipa/Database/Model/CoreData/ImageBox+CoreDataClass.swift
  MacroPepelelipa/Database/Model/CoreData/Note+CoreDataClass.swift
  MacroPepelelipa/Database/Model/CoreData/Note+CoreDataProperties.swift
  MacroPepelelipa/Database/Model/CoreData/Notebook+CoreDataClass.swift
  MacroPepelelipa/Database/Model/CoreData/TextBox+CoreDataClass.swift
  MacroPepelelipa/Database/Model/CoreData/TextBox+CoreDataProperties.swift
  MacroPepelelipa/Database/Model/CoreData/Workspace+CoreDataClass.swift
  MacroPepelelipa/Database/Model/ImageBoxObject.swift
  MacroPepelelipa/Database/Model/NoteObject.swift
  MacroPepelelipa/Database/Model/NotebookObject.swift
  MacroPepelelipa/Database/Model/TextBoxObject.swift
  MacroPepelelipa/Database/Model/WorkspaceObject.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/ResizeHandleView.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/ImageBoxView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
  MacroPepelelipa/Shared/Model/FileHelper.swift
Labels: bug, enhancement

#59 Bugfix/dark mode icon
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
Labels: enhancement

#60 hotfix/Changing device orientation check
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/UIDeviceOrientation.swift
Labels: bug

#62 Feat/text recognition
  MacroPepelelipa/Database/Model/NotebookObject.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Text Recognition/TextRecognitionManager.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Markup/ImageBoxView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupNavigationView.swift
Labels: bug, documentation, enhancement

#64 Hotfix/h1h2h3
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/h1.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/h1.imageset/h1.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/h2.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/h2.imageset/h2.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/h3.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/h3.imageset/h3.pdf
Labels: bug

#65 Fixed empty notebooks screen that wasn't showing up
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
Labels: enhancement

#66 Hotfix/scroll after new note
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewObserver.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/NotesPageViewControllerDataSource.swift
Labels: enhancement

#67 Feat/code organization
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/AlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/NotesBarButtonItems.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupFormatViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/PhotoPicker/PhotoEditingViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/NotebookIndexTableViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupTextFieldDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/AddNewSpaceTextFieldDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PopupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/ColorSelectionCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceCellNotebookCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Fonts.swift
  MacroPepelelipa/MacroPepelelipa/Model/NotebookIndex/TableViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/BoxView.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/NotesPageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/CGPointExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/CGRectExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/CornerEnum.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/Resize/ResizeHandleView.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/TextEditingDelegateObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/AddNotebook/ColorSelectionCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspaceCellNotebookCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/ImageBoxView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupFormatView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupNavigationView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextField.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToggleButton.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookView.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/AddNewSpaceToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/AddNotebook/ColorSelectionCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/EmptyScreenView.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCellNotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
  MacroPepelelipa/Shared/Model/FileHelper.swift
Labels: documentation, enhancement

#68 hotfix/Generating infinite constraints
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/PhotoPicker/PhotoEditingViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
Labels: documentation, enhancement

#69 Setting current note in IndexObserver function
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
Labels: enhancement

#71 Feat/markdown annotation
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
Labels: enhancement

#73 Setting button title label to adjust to button width
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
Labels: enhancement

#72 Feat/delete note
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/NotesPageViewControllerDataSource.swift
Labels: enhancement

#75 hotfix/text transcription in the same line
  MacroPepelelipa/MacroPepelelipa/Controller/Text Recognition/TextRecognitionManager.swift
Labels: enhancement

#76 Fixing placeholder
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/String.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
Labels: enhancement

#77 Hotfix/workspace notebook not showing empty when all deleted
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
Labels: enhancement

#79 Feat/mac catalyst basics
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/Contents.json
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_128x128.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_128x128@2x.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_16x16.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_16x16@2x.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_256x256.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_256x256@2x.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_32x32.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_32x32@2x.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_512x512.png
  MacroPepelelipa/MacroPepelelipa/Assets.xcassets/AppIcon.appiconset/icon_512x512@2x.png
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/PhotoPickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/MacroPepelelipa.entitlements
Labels: bug, enhancement

#80 Hotfix/adding boxes
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/PhotoPickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
Labels: enhancement

#81 hotfix/dismissing note placeholder
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
Labels: enhancement

#82 Adding localized names
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/en.lproj/InfoPlist.strings
  MacroPepelelipa/MacroPepelelipa/pt-BR.lproj/InfoPlist.strings
Labels: enhancement

#83 Hotfix/text view scroll view
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
Labels: documentation

#84 Feat/lock onboarding
  MacroPepelelipa/Database/EntityProtocols/WorkspaceEntity.swift
  MacroPepelelipa/Database/Model/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  MacroPepelelipa/Database/Model/CoreData/Workspace+CoreDataProperties.swift
  MacroPepelelipa/Database/Model/WorkspaceObject.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: enhancement

#85 Hotfix/text view delete behaviour
  MacroPepelelipa/Database/Model/CoreData/Workspace+CoreDataProperties.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
Labels: enhancement

#86 Feat/change nav
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/NotesBarButtonItems.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
Labels: documentation, enhancement

#87 Feat/note toolbar
  MacroPepelelipa/Database/Model/CoreData/Workspace+CoreDataProperties.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: documentation, enhancement

#88 Feat/update read me
  Color_and_Relation_Guide.jpg
  Database_Diagram.jpg
  Purple_Notebook_Diagram.jpg
  README.md
Labels: documentation

#89 Hotfix/text editing crashes+replace diagram image
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  Purple_Notebook_Diagram.jpg
Labels: enhancement

#90 Hotfix/refactoring adding workspace, notebooks and notes popups and color palette constraints
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PopupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/ColorSelectionCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/View/Workspace/AddNotebook/ColorSelectionCollectionViewCell.swift
Labels: enhancement

#91 Hotfix/lists
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Lists/MarkdownList.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
Labels: bug, documentation, enhancement

#93 Hotfix/notebook color selection
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/GestureDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
Labels: documentation, enhancement

#94 hotfix/gotToNewNote
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
Labels: enhancement

#95 Feat/entity edition
  MacroPepelelipa/Database/EntityProtocols/NotebookEntity.swift
  MacroPepelelipa/Database/EntityProtocols/WorkspaceEntity.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/EditableCollectionView.swift
  MacroPepelelipa/MacroPepelelipa/Controller/EditableCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: documentation

#96 Hotfix/placeholder constraints
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Default-notebook.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Default-notebook.imageset/Default notebook.pdf
  MacroPepelelipa/MacroPepelelipa/View/Workspace/EmptyScreenView.swift
Labels: enhancement

#98 hotfix/NSAttributedString Transformer
  MacroPepelelipa/Database/Data/CoreData/CoreDataController.swift
  MacroPepelelipa/Database/Model/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  MacroPepelelipa/Database/Model/CoreData/NSAttributedString Transformer.swift
  MacroPepelelipa/Database/Model/CoreData/Note+CoreDataProperties.swift
  MacroPepelelipa/Database/Model/CoreData/TextBox+CoreDataProperties.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
Labels: enhancement

#99 Hotfix/reposition popup when editing
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
Labels: documentation, enhancement

#100 Feat/export pdf
  MacroPepelelipa/Database/EntityProtocols/NoteEntity.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/NoteEntityToPDFExtension.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/NotebookEntityToPDFExtension.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: documentation, enhancement

#101 Hotfix/swipe keyboard + highlight
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Code/MarkdownCode+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/TextBoxView.swift
Labels: bug, enhancement

#104 Hotfix/Fixing double constraint init
  MacroPepelelipa/MacroPepelelipa/Controller/Search/SearchResultCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Search/SearchResultViewController.swift
Labels: enhancement
