Repository Pepelelipa/MacroChallenge, pull requests merged in 2020-11, with the labels that each got.

#105 feat/AddingH1ToIndexes
  MacroPepelelipa/Database/Data/CoreData/CoreDataController.swift
  MacroPepelelipa/Database/Model/CoreData/NSAttributedString Transformer.swift
  MacroPepelelipa/Database/Model/NotebookObject.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Model/Fonts.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/Shared/Model/Font.swift
Labels: bug, enhancement

#108 Feat/horizontal continuos scroll
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
Labels: documentation, enhancement

#110 Feat/custom image editing
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/AlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/ImagePickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/PhotoPickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: documentation, enhancement

#115 Hotfix/changing transcripted text format
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Text Recognition/TextRecognitionManager.swift
Labels: documentation, enhancement

#116 Feat/dark mode colors
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/Shared/App-Markdown/Colors.xcassets/Highlight.colorset/Contents.json
Labels: enhancement

#117 Feat/menu actions
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MarkdownText/View/MarkdownTextView.swift
Labels: enhancement

#118 Feat/toolbar interactions
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownBarConfiguration.swift
Labels: enhancement

#120 Added keyboard shortcuts to format the text in the text view
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MarkdownText/View/MarkdownTextView.swift
Labels: documentation, enhancement

#122 Feat/test flight v5
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/AlertController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Search/SearchResultCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: enhancement

#123 Hotfix/delete note
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: enhancement

#125 Feat/refactor pop ups
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
Labels: enhancement

#126 Feat/drag and drop for iPadOS
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/DropInteractionDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
Labels: bug, enhancement

#127 Feat/custom image edit
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/ImagePickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
Labels: enhancement

#129 Feat/pull down menus
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/DropInteractionDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownNavigationView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownToolBar.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: documentation, enhancement

#131 Added multiple windows support
  MacroPepelelipa/MacroPepelelipa/Info.plist
Labels: enhancement

#132 Feat/accessibility
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/NotebookIndexTableViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/NotebookIndex/TableViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/AddNotebook/ColorSelectionCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownFormatView.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: documentation, enhancement

#133 Feat/multitasking
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Search/SearchResultViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceCellNotebookCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspaceCellNotebookCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCellNotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: documentation, enhancement

#134 Feat/menu bar
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/EditableCollectionView.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/MenuController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: bug, documentation, enhancement

#136 Feat/multitaskingForTheEntireApp
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Search/SearchResultCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Search/SearchResultViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/AddWorkspace/AddWorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspacesCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Search/SearchResultCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: documentation, enhancement

#137 hotfix/Including ItemSizeHelper file
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/ItemSizeHelper.swift
Labels: documentation, enhancement

#138 Feat/file handling
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/MenuController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/DocumentPickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Search/SearchResultCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksCollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/MacroPepelelipa.entitlements
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MarkdownText/Model/Font Style Extension.swift
Labels: documentation, enhancement

#139 Hotfix/dark mode image
  MacroPepelelipa/MacroPepelelipa/Controller/MenuController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Bold Tip.imageset/Bold tip dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Bold Tip.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Highlighted Tip.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Highlighted Tip.imageset/Highlight tip dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Format English Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Format English Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Format Portuguese Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Format Portuguese Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Group 183@1x.png
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Group 183@2x.png
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/InputViewAsset.imageset/Group 183@3x.png
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Italic Tip.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Italic Tip.imageset/Italic tip dark.pdf
Labels: enhancement

#140 Hotfix/present edit button item
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
Labels: documentation, enhancement

#130 Feat/cloud kit
  MacroPepelelipa/Database/Data/CloudKit/CloudKitDataConnector.swift
  MacroPepelelipa/Database/Data/CloudKit/CloudKitDataController.swift
  MacroPepelelipa/Database/Data/Conflict Handler.swift
  MacroPepelelipa/Database/Data/CoreData/CoreDataController.swift
  MacroPepelelipa/Database/Data/CoreData/NSPersistantContainer.swift
  MacroPepelelipa/Database/Data/DataManager.swift
  MacroPepelelipa/Database/Data/DataSynchronizer.swift
  MacroPepelelipa/Database/Data/Errors/ImageBoxError.swift
  MacroPepelelipa/Database/Data/Errors/PersistentError.swift
  MacroPepelelipa/Database/Data/Errors/TextBoxError.swift
  MacroPepelelipa/Database/Data/Errors/WorkspaceError.swift
  MacroPepelelipa/Database/EntityProtocols/ImageBoxEntity.swift
  MacroPepelelipa/Database/EntityProtocols/ModifiableEntity.swift
  MacroPepelelipa/Database/EntityProtocols/NoteEntity.swift
  MacroPepelelipa/Database/EntityProtocols/NotebookEntity.swift
  MacroPepelelipa/Database/EntityProtocols/ObservableEntity.swift
  MacroPepelelipa/Database/EntityProtocols/PersistentEntity.swift
  MacroPepelelipa/Database/EntityProtocols/TextBoxEntity.swift
  MacroPepelelipa/Database/EntityProtocols/WorkspaceEntity.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/CloudKitEntity.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/CloudKitObject.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/QueryAnswers/DataActionAnswer.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/QueryAnswers/DataFetchAnswer.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/Record Types/Data Property.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/Record Types/ReferenceField.swift
  MacroPepelelipa/Database/Model/CloudKit/Base/Record Types/ReferenceList.swift
  MacroPepelelipa/Database/Model/CloudKit/CloudKitImageBox.swift
  MacroPepelelipa/Database/Model/CloudKit/CloudKitNote.swift
  MacroPepelelipa/Database/Model/CloudKit/CloudKitNotebook.swift
  MacroPepelelipa/Database/Model/CloudKit/CloudKitTextBox.swift
  MacroPepelelipa/Database/Model/CloudKit/CloudKitWorkspace.swift
  MacroPepelelipa/Database/Model/CoreData-CloudKit Operators.swift
  MacroPepelelipa/Database/Model/CoreData/DataModel.xcdatamodeld/DataModel.xcdatamodel/contents
  MacroPepelelipa/Database/Model/CoreData/ImageBox+CoreDataProperties.swift
  MacroPepelelipa/Database/Model/CoreData/TextBox+CoreDataProperties.swift
  MacroPepelelipa/Database/Model/ImageBoxObject.swift
  MacroPepelelipa/Database/Model/NoteObject.swift
  MacroPepelelipa/Database/Model/NotebookObject.swift
  MacroPepelelipa/Database/Model/TextBoxObject.swift
  MacroPepelelipa/Database/Model/WorkspaceObject.swift
  MacroPepelelipa/Database/Model/en.lproj/Localizable.strings
  MacroPepelelipa/Database/Model/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/MacroPepelelipa.entitlements
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Workspace/WorkspaceCollectionViewCell.swift
Labels: documentation

#141 Feat/onboarding
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Extensions/NotesBarButtonItems.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Onbording/OnboardingPageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Devices Image.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Devices Image.imageset/Device Image.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Format Image English.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Format Image English.imageset/Transcript Image English Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Format Image English.imageset/Transcript Image English Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Format Image Portuguese.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Format Image Portuguese.imageset/Transcript Image Portuguese Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Format Image Portuguese.imageset/Transcript Image Portuguese Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Markdown Image English.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Markdown Image English.imageset/Markdown Image En2.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Markdown Image English.imageset/Markdown Image English.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Markdown Image Portuguese.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Markdown Image Portuguese.imageset/Markdown Image Pt2.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Markdown Image Portuguese.imageset/Markdown Image.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Transcript Image English.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Transcript Image English.imageset/Transcript Image English Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Transcript Image English.imageset/Transcript Image English Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Transcript Image Portuguese.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Transcript Image Portuguese.imageset/Transcript Image Portuguese Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Transcript Image Portuguese.imageset/Transcript Image Portuguese Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Workspace Image English.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Workspace Image English.imageset/Workspace Image English Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Workspace Image English.imageset/Workspace Image English Light.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Workspace Image Portuguese.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Workspace Image Portuguese.imageset/Workspace Image Portuguese Dark.pdf
  MacroPepelelipa/MacroPepelelipa/View/Media.xcassets/Workspace Image Portuguese.imageset/Workspace Image Portuguese Light.pdf
Labels: documentation, enhancement

#142 Hotfix/collection item size
  MacroPepelelipa/MacroPepelelipa/Controller/ItemSizeHelper.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
Labels: enhancement

#143 Hotfix/pop over
  MacroPepelelipa/Database/Data/Conflict Handler.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownContainerView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownFormatView.swift
Labels: enhancement

#144 Hotfix/markdown bug fixes
  MacroPepelelipa/Database/Data/DataManager.swift
  MacroPepelelipa/Database/Model/ImageBoxObject.swift
  MacroPepelelipa/Database/Model/NoteObject.swift
  MacroPepelelipa/Database/Model/NotebookObject.swift
  MacroPepelelipa/Database/Model/TextBoxObject.swift
  MacroPepelelipa/Database/Model/WorkspaceObject.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/BoldElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/BulletListElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/HeaderElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/HighlightElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/ItalicElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/NumericListElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/Elements/UnderlineElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/MarkdownElement.swift
  MacroPepelelipa/MarkdownText/Model/Parser/MarkdownParser.swift
  MacroPepelelipa/MarkdownText/View/MarkdownTextView.swift
  MacroPepelelipa/Shared/App-Markdown/AttributedString Extension.swift
  MacroPepelelipa/Shared/App-Markdown/Colors.swift
Labels: bug, documentation, wontfix

#145 hotfix/onboarding-Animation
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/Onbording/OnboardingPageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: enhancement

#149 Feat/headers on index
  MacroPepelelipa/Database/Model/NotebookObject.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/MarkdownText/Model/Font Style Extension.swift
Labels: enhancement

#148 Feat/ck subscriptions deletion
  MacroPepelelipa/Database/Data/CloudKit/CloudKitDataController.swift
  MacroPepelelipa/Database/Data/CoreData/CoreDataController.swift
  MacroPepelelipa/Database/Data/DataManager.swift
  MacroPepelelipa/Database/Data/EntityObserver.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/NotebooksSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelection/WorkspaceSelectionViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/Notes/NotesPageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notifications/CKSubscriptionsController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/NotebooksCollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/WorkspacesCollectionViewDataSource.swift
Labels: enhancement

#150 hotfix/notesTitle-H1
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/AddNoteViewController.swift
Labels: enhancement

#152 Hotfix/mac constraints
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceSelected/AddNotebook/AddNotebookViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
Labels: enhancement

#155 Hotfix/drag and drop and images for mac
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/DropInteractionDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/LooseNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/MacroPepelelipa.entitlements
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Markdown/MarkdownBarConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: documentation, enhancement

#156 Hotfix/increasing vision accuracy
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/LooseNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Text Recognition/TextRecognitionManager.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/MarkupToolBarObserver.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: enhancement

#157 Hotfix/share button for mac
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupContainerViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/LooseNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Notes/NotesToolbar.swift
Labels: enhancement

#158 Hotfix/note title and placeholder
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/LooseNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: enhancement

#159 Hotfix/AppStore version minor bug fixes
  MacroPepelelipa/Database/Data/CloudKit/CloudKitDataController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Accessories/NotesViewControllerConfiguration.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/LooseNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Markdown/TextBoxView.swift
  MacroPepelelipa/MarkdownText/Controller/MarkdownTextViewDelegate.swift
  MacroPepelelipa/MarkdownText/View/MarkdownTextView.swift
  MacroPepelelipa/Shared/App-Markdown/AttributedString Extension.swift
Labels: enhancement

#161 Feat/changing-version
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Info.plist
Labels: enhancement

#162 hotfix/infoplist
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Info.plist
Labels: enhancement

#164 Added navigation controller with done button on TipViewController
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/TipViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/TextEditingContainerViewController.swift
Labels: enhancement

#163 Hotfix/image from camera
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/ImagePickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
Labels: enhancement

#165 Change in the version
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/en.lproj/InfoPlist.strings
  MacroPepelelipa/MacroPepelelipa/pt-BR.lproj/InfoPlist.strings
Labels: enhancement

#172 Feat/mac app store
  MacroPepelelipa/Database/Info.plist
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/Search/SearchResultEnum.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MarkdownText/Info.plist
Labels: bug, enhancement

#173 Hotfix/toolbar on mac
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes Page View/NotesPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/ImageButtonObserver.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/LooseNoteViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController/Controllers/NotesViewController.swift
Labels: enhancement

#174 Feat/onboarding corrections
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingPageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Onboarding/OnboardingViewController.swift
Labels: bug
