Repository Pepelelipa/MacroChallenge, pull requests merged in 2020-09, with the labels that each got.

#1 Update README.md
  README.md
Labels: documentation

#3 Added SwiftLint file
  .swiftLint.yml
Labels: documentation

#4 Adding PR template
  pull_request_template.md
Labels: documentation, enhancement

#5 Adding project
  .gitignore
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Base.lproj/LaunchScreen.storyboard
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/AppIcon.appiconset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Base.lproj/Main.storyboard
Labels: documentation, enhancement

#6 Updating lint
  MacroPepelelipa/.swiftLint.yml
Labels: enhancement

#7 Feat/notebook collection
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa.xcodeproj/xcshareddata/xcschemes/MacroPepelelipa.xcscheme
  MacroPepelelipa/MacroPepelelipa/AppDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/CollectionView/Delegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PageControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/ViewController.swift
  MacroPepelelipa/MacroPepelelipa/Info.plist
  MacroPepelelipa/MacroPepelelipa/Model/ColorExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/CollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/PageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Base.lproj/Main.storyboard
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
Labels: enhancement

#8 Feat/adding localizables
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa.xcodeproj/xcshareddata/xcschemes/MacroPepelelipa-BR.xcscheme
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/ViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/StringExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
Labels: enhancement

#9 Feat/notebook view
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa.xcodeproj/xcshareddata/xcschemes/MacroPepelelipa-BR.xcscheme
  MacroPepelelipa/MacroPepelelipa.xcodeproj/xcshareddata/xcschemes/MacroPepelelipa.xcscheme
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexDelegateProtocol.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/SplitView/SplitViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/NotebookIndex/TableViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
Labels: enhancement

#10 Adding print to lint
  MacroPepelelipa/.swiftLint.yml
Labels: enhancement

#11 Removing Setup - Adding Documentation
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/SplitView/SplitViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/CollectionView/CollectionViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PageControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/ColorExtension.swift
  MacroPepelelipa/MacroPepelelipa/Model/NotebookIndex/TableViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/CollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/PageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
Labels: documentation

#12 Feat/markup
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/PhotoPicker/MarkupPhotoPickerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/PhotoPicker/PhotoEditingViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Bold/MarkdownBold.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/ColoredBackground/Code/MarkdownCode.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/ColoredBackground/Highlight/MarkdownHighlight.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/ColoredBackground/MarkdownColoredBackground.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Escaping/MarkdownCodeEscaping.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Escaping/MarkdownEscaping.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Escaping/MarkdownUnescaping.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Header/MarkdownHeader.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Italic/MarkdownItalic.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Link/MarkdownAutomaticLink.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Link/MarkdownLink.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/List/MarkdownList.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Quote/MarkdownQuote.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Strikethrough/MarkdownStrikethrough.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Extensions/String+UTF16.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownParser.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownCommonElement.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownElement.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownLevelElement.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownLinkElement.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownStyle.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Code/MarkdownCode+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Header/MarkdownHeader+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Link/MarkdownLink+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Extensions/UIFont+Traits.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/MarkdownParser+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Typealias+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/Strings/en.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/Model/Strings/pt-BR.lproj/Localizable.strings
  MacroPepelelipa/MacroPepelelipa/SceneDelegate.swift
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Background.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Body.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Highlight.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Placeholder.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Title.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/Tools.colorset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextField.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
Labels: bug, documentation, enhancement

#13 Feat/database structure
  MacroPepelelipa/Database/Database.h
  MacroPepelelipa/Database/Entities/ImageBox.swift
  MacroPepelelipa/Database/Entities/Note.swift
  MacroPepelelipa/Database/Entities/Notebook.swift
  MacroPepelelipa/Database/Entities/TextBox.swift
  MacroPepelelipa/Database/Entities/Workspace.swift
  MacroPepelelipa/Database/EntityProtocols/ImageBoxEntity.swift
  MacroPepelelipa/Database/EntityProtocols/NoteEntity.swift
  MacroPepelelipa/Database/EntityProtocols/NotebookEntity.swift
  MacroPepelelipa/Database/EntityProtocols/TextBoxEntity.swift
  MacroPepelelipa/Database/EntityProtocols/WorkspaceEntity.swift
  MacroPepelelipa/Database/Info.plist
  MacroPepelelipa/Database/Mockup/Mockdata.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/SplitView/SplitViewController.swift
  MacroPepelelipa/Shared/Model/ColorExtension.swift
  MacroPepelelipa/Shared/Model/StringExtension.swift
Labels: enhancement

#15 Fix/conforming project to database
  MacroPepelelipa/Database/Entities/Notebook.swift
  MacroPepelelipa/Database/Entities/NotebookIndex.swift
  MacroPepelelipa/Database/EntityProtocols/NoteEntity.swift
  MacroPepelelipa/Database/EntityProtocols/NotebookEntity.swift
  MacroPepelelipa/Database/EntityProtocols/NotebookIndexEntity.swift
  MacroPepelelipa/Database/EntityProtocols/WorkspaceEntity.swift
  MacroPepelelipa/Database/Mockup/Mockdata.swift
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/SplitView/SplitViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PageControllerDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/PageViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/NotebookIndex/TableViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/CollectionViewDataSource.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/PageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
  MacroPepelelipa/MacroPepelelipa/View/Workspace/NotebookCollectionViewCell.swift
  MacroPepelelipa/Shared/Model/ColorExtension.swift
Labels: documentation, enhancement

#14 Feat/image button
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/imageButton.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/imageButton.imageset/imageButton.pdf
Labels: enhancement

#17 Feat/image button
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/MarkupTextFieldDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notes/NotesViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Notes/TextEditingDelegateObserver.swift
Labels: enhancement

#16 Fixing SplitView constraint and unwoned self
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/SplitView/SplitViewController.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Workspace/WorkspaceViewController.swift
Labels: bug

#18 Feat/lists
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/List/MarkdownList.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Lists/MarkdownList.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Lists/MarkdownNumeric.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Quote/MarkdownQuote.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownParser.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownLevelElement.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Extensions/UIFont+Traits.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/MarkdownParser+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
Labels: bug, documentation, enhancement

#20 Feat/headers
  MacroPepelelipa/MacroPepelelipa.xcodeproj/project.pbxproj
  MacroPepelelipa/MacroPepelelipa/Controller/Markup/MarkupTextViewDelegate.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Elements/Header/MarkdownHeader.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownEditor.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/MarkdownParser.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/Common/Protocols/MarkdownLevelElement.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Elements/Header/MarkdownHeader+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/Extensions/UIFont+Traits.swift
  MacroPepelelipa/MacroPepelelipa/Model/MarkupKit/UIKit/MarkdownParser+UIKit.swift
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/H1.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/H1.imageset/H1.pdf
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/H2.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/H2.imageset/H2.pdf
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/H3.imageset/Contents.json
  MacroPepelelipa/MacroPepelelipa/View/Assets.xcassets/H3.imageset/H3.pdf
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupTextView.swift
  MacroPepelelipa/MacroPepelelipa/View/Markup/MarkupToolBar.swift
Labels: documentation, enhancement

#19 Feat/design note index
  MacroPepelelipa/Database/Entities/Notebook.swift
  MacroPepelelipa/Database/Entities/NotebookIndex.swift
  MacroPepelelipa/Database/EntityProtocols/NotebookIndexEntity.swift
  MacroPepelelipa/MacroPepelelipa/Controller/Notebook/Notebook Index/IndexViewController.swift
  MacroPepelelipa/MacroPepelelipa/Model/Workspace/PageViewControllerDataSource.swift
  MacroPepelelipa/MacroPepelelipa/View/NotebookIndex/NotebookIndexTableViewCell.swift
Labels: enhancement
